---
- name:  Gather facts from all hosts
  hosts: all
  tasks:
  - name: Gather facts from controller
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['master'] }}"
  - name: Gather facts from worker
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['worker'] }}"
  - name: Gather facts from etcd
    setup:
    delegate_to: "{{ item }}"
    delegate_facts: True
    loop: "{{ groups['etcd'] }}"

- hosts: k8s_ca
  roles:
    -
      role: githubixx.cfssl
      tags: role-cfssl
    -
      role: githubixx.kubernetes-ca
      tags: [ role-kubernetes-ca, role-kubernetes-ca-etcd ]

- hosts: etcd
  become: yes
  roles:
    -
      role: githubixx.etcd
      tags: role-etcd

- hosts: cluster
  become: yes
  roles:
    - docker
    - kube

- hosts: master
  become: yes
  roles:
    - master

- hosts: worker
  become: yes
  roles:
    - cluster
